name: Build DocuMerge Pro Cross-Platform Installers

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build-windows:
    name: Build Windows Installer
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    # ✅ NEW: Set up Google Sheets credentials from environment variable
    - name: Set up Google Sheets credentials
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}' > service-account-key.json
      shell: bash
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      
    - name: Create Windows installer
      run: mvn jpackage:jpackage
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      
    - name: Upload Windows installer
      uses: actions/upload-artifact@v4
      with:
        name: documerge-pro-windows
        path: target/dist/*.exe
        retention-days: 30

  build-linux:
    name: Build Linux Installer
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Install packaging tools
      run: |
        sudo apt-get update
        sudo apt-get install -y fakeroot
        
    # ✅ NEW: Set up Google Sheets credentials from environment variable
    - name: Set up Google Sheets credentials
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}' > service-account-key.json
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      
    - name: Create Linux installer
      run: mvn jpackage:jpackage
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      
    - name: Upload Linux installer
      uses: actions/upload-artifact@v4
      with:
        name: documerge-pro-linux
        path: target/dist/*.deb
        retention-days: 30

  build-macos:
    name: Build macOS Installer
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    # ✅ NEW: Set up Google Sheets credentials from environment variable
    - name: Set up Google Sheets credentials
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}' > service-account-key.json
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      
    - name: Create macOS installer
      run: mvn jpackage:jpackage
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      
    - name: Upload macOS installer
      uses: actions/upload-artifact@v4
      with:
        name: documerge-pro-macos
        path: target/dist/*.dmg
        retention-days: 30

  create-release:
    name: Create Release with All Installers
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-macos]
    if: github.event_name == 'release'
    
    steps:
    - name: Download Windows installer
      uses: actions/download-artifact@v4
      with:
        name: documerge-pro-windows
        path: ./installers/windows/
        
    - name: Download Linux installer
      uses: actions/download-artifact@v4
      with:
        name: documerge-pro-linux
        path: ./installers/linux/
        
    - name: Download macOS installer
      uses: actions/download-artifact@v4
      with:
        name: documerge-pro-macos
        path: ./installers/macos/
        
    - name: Display downloaded files
      run: |
        echo "Windows installer:"
        ls -la ./installers/windows/
        echo "Linux installer:"
        ls -la ./installers/linux/
        echo "macOS installer:"
        ls -la ./installers/macos/
        
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./installers/windows/*
          ./installers/linux/*
          ./installers/macos/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
